import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import PrelineScript from "./components/PrelineScript";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MunSci LiBro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-200 dark:bg-neutral-900 text-black dark:text-neutral-200`}
      >
        {children}
      </body>
      <PrelineScript />
    </html>
  );
}
